[workspace]
resolver = "2"
members = [
    "solver",
    "algorithms",
    "structures",
    "integers",
    "number_theory",
    "number_lists",
]

[workspace.dependencies]
itertools = "0.12.1"
num-integer = "0.1.46"
num-traits = "0.2.18"
